using System;
using System.Collections.Generic;

static class Config
{
    public static readonly Dictionary<string, HashSet<string>> Roster = new(StringComparer.OrdinalIgnoreCase)
    {
        ["CENTRAL PROVINCE"] = new("CHIBOMBO,CHISAMBA,CHITAMBO,KABWE,KAPIRI MPOSHI,LUANO,MKUSHI,MUMBWA,NGABWE,SERENJE,SHIBUYUNJI".Split(',')),
        ["COPPERBELT PROVINCE"] = new("CHILILABOMBWE,CHINGOLA,KALULUSHI,KITWE,LUANSHYA,LUFWANYAMA,MASAITI,MPONGWE,MUFULIRA,NDOLA".Split(',')),
        ["EASTERN PROVINCE"] = new("CHADIZA,CHASEFU,CHIPANGALI,CHIPATA,KASENENGWA,KATETE,LUMEZI,LUNDAZI,LUSANGAZI,MAMBWE,NYIMBA,PETAUKE,SINDA,VUBWI".Split(',')),
        ["LUAPULA PROVINCE"] = new("CHEMBE,CHIENGE,CHIFUNABULI,CHIPILI,KAWAMBWA,LUNGA,MANSA,MILENGE,MWANSABOMBWE,MWENSE,NCHELENGE,SAMFYA".Split(',')),
        ["LUSAKA PROVINCE"] = new("CHILANGA,CHONGWE,KAFUE,LUANGWA,LUSAKA,RUFUNSA".Split(',')),
        ["MUCHINGA PROVINCE"] = new("CHAMA,CHINSALI,ISOKA,KANCHIBIYA,LAVUSHIMANDA,MAFINGA,MPIKA,NAKONDE,SHIWANG'ANDU".Split(',')),
        ["NORTH-WESTERN PROVINCE"] = new("CHAVUMA,IKELENGE,KABOMPO,KALUMBILA,KASEMPA,MANYINGA,MUFUMBWE,MUSHINDAMO,MWINILUNGA,SOLWEZI,ZAMBEZI".Split(',')),
        ["NORTHERN PROVINCE"] = new("CHILUBI,KAPUTA,KASAMA,LUNTE,LUPOSOSHI,LUWINGU,MBALA,MPOROKOSO,MPULUNGU,MUNGWI,NSAMA,SENGA".Split(',')),
        ["SOUTHERN PROVINCE"] = new("CHIKANKATA,CHIRUNDU,CHOMA,GWEMBE,ITEZHI-TEZHI,KALOMO,KAZUNGULA,LIVINGSTONE,MAZABUKA,MONZE,NAMWALA,PEMBA,SIAVONGA,SINAZONGWE,ZIMBA".Split(',')),
        ["WESTERN PROVINCE"] = new("KALABO,KAOMA,LIMULUNGA,LUAMPA,LUKULU,MITETE,MONGU,MULOBEZI,MWANDI,NALOLO,NKEYEMA,SENANGA,SESHEKE,SHANGOMBO,SIKONGO,SIOMA".Split(',')),
    };
}
