using System.Globalization;
using System.IO.Compression;
using System.Text;
using System.Text.Json;
using System.Xml;

var source = args.ElementAtOrDefault(0) ?? @"C:\Users\Zanga Musakuzi\Desktop\tracer dashboard\FEBRUARY-DECEMBER 2024.xlsx";
var destination = args.ElementAtOrDefault(1) ?? Path.Combine("src", "tracerFacilityData2024.js");
using var archive = ZipFile.OpenRead(source);
var strings = ReadStrings(archive);
var periods = new Dictionary<string, Period>(StringComparer.Ordinal);
var sheet = archive.GetEntry("xl/worksheets/sheet1.xml") ?? throw new Exception("Missing SUMMARY SHEET.");
using (var reader = XmlReader.Create(sheet.Open(), new XmlReaderSettings { IgnoreWhitespace = true }))
{
  string[] headers = Array.Empty<string>();
  while (reader.Read())
  {
    if (reader.NodeType != XmlNodeType.Element || reader.LocalName != "row") continue;
    var rowNumber = int.Parse(reader.GetAttribute("r") ?? "0", CultureInfo.InvariantCulture);
    var cells = ReadRow(reader.ReadSubtree(), strings);
    if (rowNumber == 1) { headers = Enumerable.Range(0, 19).Select(i => Clean(cells.GetValueOrDefault(i)) ?? $"COLUMN_{i}").ToArray(); continue; }
    if (headers.Length == 0) continue;
    var value = new Dictionary<string, string?>(StringComparer.OrdinalIgnoreCase);
    for (var i = 0; i < headers.Length; i++) value[headers[i]] = Clean(cells.GetValueOrDefault(i));
    var date = ToIso(value.GetValueOrDefault("DATE"));
    if (date is null) continue;
    var province = Province(value.GetValueOrDefault("PROVINCE"));
    var district = District(province, value.GetValueOrDefault("DISTRICT"));
    var level = Level(value.GetValueOrDefault("FACILITY LEVEL"));
    var facility = Clean(value.GetValueOrDefault("FACILITY NAME")) ?? "Unnamed reporting unit";
    ApplyVerifiedFacility(ref province, ref district, ref level, facility);
    var item = Clean(value.GetValueOrDefault("DESCRIPTION OF ITEM")) ?? "Unknown commodity";
    var programme = Program(value.GetValueOrDefault("PROGRAM"), item);
    var row = new Row(Num(value.GetValueOrDefault("QUANTITY")), Num(value.GetValueOrDefault("AMC")), Num(value.GetValueOrDefault("MOS")), Availability(value.GetValueOrDefault("AVAILABILITY")));
    if (!periods.TryGetValue(date, out var period)) periods[date] = period = new Period(date);
    period.Add(province, district, level, facility, programme, item, row);
  }
}
var output = periods.Values.OrderBy(p => p.Date).Select(p => p.Export()).ToList();
Directory.CreateDirectory(Path.GetDirectoryName(destination) ?? ".");
File.WriteAllText(destination, "export const tracerReportingPeriods = " + JsonSerializer.Serialize(output, new JsonSerializerOptions { WriteIndented = false }) + ";\n");
Console.WriteLine($"Generated {output.Count} historical periods from {source}.");

static List<string> ReadStrings(ZipArchive zip) { var entry=zip.GetEntry("xl/sharedStrings.xml")!; var result=new List<string>(); using var r=XmlReader.Create(entry.Open(),new XmlReaderSettings{IgnoreWhitespace=true}); while(r.Read()) if(r.NodeType==XmlNodeType.Element&&r.LocalName=="si"){ using var sub=r.ReadSubtree(); var b=new StringBuilder(); while(sub.Read()) if(sub.NodeType==XmlNodeType.Element&&sub.LocalName=="t") b.Append(sub.ReadElementContentAsString()); result.Add(b.ToString()); } return result; }
static Dictionary<int,string?> ReadRow(XmlReader r,IReadOnlyList<string> strings){var values=new Dictionary<int,string?>();while(r.Read())if(r.NodeType==XmlNodeType.Element&&r.LocalName=="c"){var reference=r.GetAttribute("r")??"";var type=r.GetAttribute("t");string? raw=null;using var sub=r.ReadSubtree();while(sub.Read())if(sub.NodeType==XmlNodeType.Element&&sub.LocalName=="v"){raw=sub.ReadElementContentAsString();break;}if(raw!=null&&type=="s"&&int.TryParse(raw,out var i))raw=strings[i];values[Column(reference)]=raw;}return values;}
static int Column(string reference){var total=0;foreach(var c in reference.TakeWhile(char.IsLetter))total=total*26+char.ToUpperInvariant(c)-'A'+1;return total-1;}
static string? Clean(string? value)=>string.IsNullOrWhiteSpace(value)?null:string.Join(' ',value.Split((char[]?)null,StringSplitOptions.RemoveEmptyEntries));
static double? Num(string? value)=>double.TryParse((value??"").Replace(",",""),NumberStyles.Float,CultureInfo.InvariantCulture,out var n)?n:null;
static double? Availability(string? value){var n=Num((value??"").TrimEnd('%'));if(n is null)return null;var v=n>1?n/100:n;return Math.Clamp(v.Value,0,1);}
static string? ToIso(string? value)=>Num(value) is double d?DateTime.FromOADate(d).ToString("yyyy-MM-dd"):null;
static string Province(string? value){var v=(Clean(value)??"UNKNOWN").ToUpperInvariant();return v switch{"EASTERN PRVONCE"=>"EASTERN PROVINCE","NORTHWESTERN PROVINCE"=>"NORTH-WESTERN PROVINCE","CENTRAL"=>"CENTRAL PROVINCE","COPPERBELT"=>"COPPERBELT PROVINCE","EASTERN"=>"EASTERN PROVINCE","LUAPULA"=>"LUAPULA PROVINCE","LUSAKA"=>"LUSAKA PROVINCE","MUCHINGA"=>"MUCHINGA PROVINCE","NORTHERN"=>"NORTHERN PROVINCE","SOUTHERN"=>"SOUTHERN PROVINCE","WESTERN"=>"WESTERN PROVINCE",_=>v};}
static string District(string province,string? value){var d=(Clean(value)??"UNKNOWN").ToUpperInvariant().Replace("`","'");d=System.Text.RegularExpressions.Regex.Replace(d,"\\s+DISTRICT$","");d=d switch{"KAPIRI"=>"KAPIRI MPOSHI","ITEZHI TEZHI"=>"ITEZHI-TEZHI","CHKANKATA"=>"CHIKANKATA","SINZONGWE"=>"SINAZONGWE","NAWMALA"=>"NAMWALA","SHIWANG'ANDU"=>"SHIWANG'ANDU",_=>d};return Config.Roster.TryGetValue(province,out var districts)&&districts.Contains(d)?d:"UNKNOWN";}
static string Level(string? value){var v=(Clean(value)??"").ToUpperInvariant();if(v.Contains("HEALTH POST"))return "HEALTH POST";if(v.Contains("HEALTH CENTRE")||v.Contains("HEALTH CENTER"))return "HEALTH CENTRE";if(v.Contains("CANCER"))return "CANCER DISEASES HOSPITAL";if(v.Contains("HEART"))return "NATIONAL HEART HOSPITAL";if(v.Contains("WOMEN")||v.Contains("NEW BORN"))return "WOMEN AND NEWBORN HOSPITAL";if(v.Contains("RENAL"))return "RENAL UNITS";if(v.Contains("MENTAL"))return "MENTAL HEALTH UNITS";if(v.Contains("OPTH")||v.Contains("OPHTH")||v.Contains("EYE"))return "EYE/OPHTHALMOLOGY HOSPITAL";if(v.Contains("TB")||v.Contains("MDR"))return "TB-DS/TB-MDR UNITS";if(v.Contains("LEVEL 2")||v.Contains("GENERAL"))return "LEVEL 2/GENERAL HOSPITAL";if(v.Contains("LEVEL 3")||v.Contains("TERTIARY")||v.Contains("PAEDIATRIC")||v.Contains("ADULT"))return "LEVEL 3 HOSPITAL";if(v.Contains("LEVEL 1")||v.Contains("DISTRICT LEVEL"))return "LEVEL 1 HOSPITAL";return "PRIMARY CARE - NOT SPECIFIED";}
static string Program(string? value,string item){var p=(Clean(value)??"Unknown programme").ToUpperInvariant();if(new[]{"TB0MDR","TBMDR","MDRTB"}.Contains(p.Replace("-","").Replace(" ","")))return "TB-MDR";if(new[]{"TB0DS","TBDS","DSTB"}.Contains(p.Replace("-","").Replace(" ","")))return "TB-DS";var art=new[]{"ABACAVIR","LAMIVUDINE","DOLUTEGRAVIR","TENOFOVIR","EFAVIRENZ","NEVIRAPINE","LOPINAVIR","RITONAVIR","ZIDOVUDINE"};return art.Any(t=>p.Contains(t)||item.ToUpperInvariant().Contains(t))?"ART":p is "#REF!" or "REF"?"Unknown programme":p;}
static void ApplyVerifiedFacility(ref string province,ref string district,ref string level,string facility){var f=facility.ToUpperInvariant();if(f.Contains("ARTHUR")&&(f.Contains("DAVISON")||f.Contains("DAVIDSON"))){province="COPPERBELT PROVINCE";district="NDOLA";level="LEVEL 3 HOSPITAL";}else if(f.Contains("CHAINAMA")){province="LUSAKA PROVINCE";district="LUSAKA";level="MENTAL HEALTH UNITS";}else if(f.Contains("CHADIZA DISTRICT")){province="EASTERN PROVINCE";district="CHADIZA";level="LEVEL 1 HOSPITAL";}else if(f.Contains("CHAVUMA DISTRICT")){province="NORTH-WESTERN PROVINCE";district="CHAVUMA";level="LEVEL 1 HOSPITAL";}else if(f.Contains("CHAMA DISTRICT")){province="MUCHINGA PROVINCE";district="CHAMA";level="LEVEL 1 HOSPITAL";}else if(f.Contains("KAFUE GENERAL")){province="LUSAKA PROVINCE";district="KAFUE";level="LEVEL 2/GENERAL HOSPITAL";} }

sealed class Bucket { public int Rows,AvailableRows,AvailabilityCount,MosCount,Stockout,NearCritical,Understocked,AccordingToPlan,AbovePlan,Overstock,DataGap; public double AvailabilitySum,MosSum,Quantity,Amc; public void Add(Row r){Rows++;Quantity+=r.Quantity??0;Amc+=r.Amc??0;if(r.Availability is double a){AvailabilitySum+=a;AvailabilityCount++;if(a>0)AvailableRows++;}if(r.Mos is double m){MosSum+=m;MosCount++;if(m<=.1)Stockout++;else if(m<1)NearCritical++;else if(m<2)Understocked++;else if(m<=4)AccordingToPlan++;else if(m>12)Overstock++;else AbovePlan++;}else DataGap++;} public Dictionary<string,object?> Export(string name,object? extra=null){var row=new Dictionary<string,object?>{{"name",name},{"rows",Rows},{"availability",AvailabilityCount==0?0:Math.Round(AvailabilitySum/AvailabilityCount,4)},{"mos",MosCount==0?0:Math.Round(MosSum/MosCount,2)},{"stockout",Stockout},{"nearCritical",NearCritical},{"understocked",Understocked},{"accordingToPlan",AccordingToPlan},{"abovePlan",AbovePlan},{"overstock",Overstock},{"dataGap",DataGap},{"quantity",Math.Round(Quantity,2)},{"amc",Math.Round(Amc,2)},{"riskRows",Stockout+NearCritical+Understocked},{"stockoutRate",Rows==0?0:Math.Round((double)Stockout/Rows,4)}};if(extra is not null)foreach(var property in extra.GetType().GetProperties())row[property.Name]=property.GetValue(extra);return row;} }
record Row(double? Quantity,double? Amc,double? Mos,double? Availability);
sealed class Period { public string Date; readonly Bucket national=new(); readonly Dictionary<string,Bucket> provinces=new(),districts=new(),levels=new(),facilities=new(),programmes=new(),commodities=new(),scopes=new(); readonly HashSet<string> districtSet=new(),facilitySet=new(); public Period(string date)=>Date=date; Bucket B(Dictionary<string,Bucket>d,string k){if(!d.TryGetValue(k,out var b))d[k]=b=new();return b;} public void Add(string p,string d,string l,string f,string prog,string item,Row r){national.Add(r);B(provinces,p).Add(r);B(districts,$"{p}|{d}").Add(r);B(levels,l).Add(r);B(facilities,$"{p}|{d}|{l}|{f}").Add(r);B(programmes,prog).Add(r);B(commodities,item).Add(r);B(scopes,$"{p}|{l}|{prog}").Add(r);districtSet.Add($"{p}|{d}");facilitySet.Add($"{p}|{d}|{l}|{f}");} public object Export(){var date=DateTime.Parse(Date);return new {id=Date,reportDate=Date,label=$"Historical report - {date:dd MMMM yyyy}",month=$"{date:yyyy-MM}",week=$"Week {((date.Day-1)/7)+1}",source="FEBRUARY-DECEMBER 2024 historical master",counts=new{rows=national.Rows,provinces=provinces.Count,districts=districtSet.Count,facilityUnits=facilitySet.Count,programmes=programmes.Count,commodities=commodities.Count},national=national.Export("Zambia"),provinces=provinces.Select(x=>x.Value.Export(x.Key)).ToList(),districts=districts.Select(x=>{var a=x.Key.Split('|');return x.Value.Export(a[1],new{province=a[0]});}).ToList(),facilityLevels=levels.Select(x=>x.Value.Export(x.Key)).ToList(),facilities=facilities.Select(x=>{var a=x.Key.Split('|');return x.Value.Export(a[3],new{province=a[0],district=a[1],facilityLevel=a[2],isAggregate=a[3].Equals("ALL",StringComparison.OrdinalIgnoreCase),stockoutItems=Array.Empty<object>(),lowStockItems=Array.Empty<object>(),accordingToPlanItems=Array.Empty<object>(),overstockItems=Array.Empty<object>(),stockoutItemCount=x.Value.Stockout,lowStockItemCount=x.Value.NearCritical+x.Value.Understocked,accordingToPlanItemCount=x.Value.AccordingToPlan,overstockItemCount=x.Value.AbovePlan+x.Value.Overstock});}).ToList(),programmes=programmes.Select(x=>x.Value.Export(x.Key)).ToList(),programmeScopes=scopes.Select(x=>{var a=x.Key.Split('|');return x.Value.Export(a[2],new{province=a[0],facilityLevel=a[1]});}).ToList(),commodities=commodities.Select(x=>x.Value.Export(x.Key,new{normalized=x.Key.ToLowerInvariant()})).ToList(),commodityFacilityData=new{dictionaries=new{provinces=Array.Empty<string>(),districts=Array.Empty<string>(),levels=Array.Empty<string>(),facilities=Array.Empty<string>(),items=Array.Empty<string>(),programmes=Array.Empty<string>()},rows=Array.Empty<object>()},comments=Array.Empty<object>(),dataQuality=new{provinces=Array.Empty<object>(),districts=Array.Empty<object>(),facilityTypes=Array.Empty<object>(),facilities=Array.Empty<object>()}};}}
